ДЗ 15
Otus-DevOps-2021-02/geckonoff_microservices pull request #2
Opened 2021-06-07 09:34 UTC by geckonoff

2021-06-08 09:01 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к файлу, дз возвращаю на доработку.

2021-06-08 09:01 UTC, mrgreyves commented on src/post-py/Dockerfile
> +ENV POST_DATABASE_HOST post_db_myal
Переопределите переменную на post_db, и запуште изменения.

2021-06-09 19:36 UTC, mrgreyves requested changes
У вас сервис post корректно работает? healthcheck доступен локально?

2021-06-10 13:28 UTC, geckonoff commented
А у вас?

2021-06-10 13:30 UTC, geckonoff commented
Валится через 4 секунды после запуска.
Пытался дебажить там выходят моножественные питоновские ошибки.
Я не спец в питоне, поэтому не могу отладить приложение.

2021-06-10 13:30 UTC, geckonoff commented
В группе никто не отвечает.

2021-07-01 16:23 UTC, mrgreyves approved these changes
Здравствуйте!) Видимо вы разобрались с ошибкой =)

2021-07-01 16:51 UTC, merged